version: "3"

services: 
  mern-auth-frontend: 
    build: ./frontend 
    container_name: mern-auth-frontend 
    restart: unless-stopped 
    expose: 
      - 3000 
    ports: 
      - "3005:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true 
      - HOST=0.0.0.0
  mern-auth-backend: 
    build: ./backend 
    container_name: mern-auth-backend 
    restart: unless-stopped 
    expose: 
      - 5000 
    ports: 
      - "5001:5000"
  mern-auth-db: 
    image: mongo:5
    container_name: mern-auth-db 
    restart: unless-stopped 
    expose: 
      - 27017
    ports: 
      - "27021:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: mernauth 